name: Fetch Grades

on:
  workflow_dispatch:
  
jobs:
  fetch-grades:
    runs-on: macos-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      - name: Install Requirements
        run: |
          python -m pip install -r requirements.txt
          
      - name: Run Script
        env:
          PSA_USERNAME: ${{ secrets.PSA_USERNAME }}
          PSA_PASSWORD: ${{ secrets.PSA_PASSWORD }}
          FTP_HOST:     ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "${{ secrets.PICKLE_FILE }}" | base64 -d > token.pickle
          echo "${{ secrets.CREDENTIALS_FILE }}" | base64 -d > credentials.json
          python basic.py
          
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Adding submissions to repo
